# Generated by Django 2.0.6 on 2018-09-04 08:09

from django.db import migrations, models
import django.db.models.deletion
import jobapply.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_resume', models.FileField(blank=True, upload_to=jobapply.models.user_attachment_directory_path)),
                ('attach_transcript', models.FileField(blank=True, upload_to=jobapply.models.user_attachment_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateBasic',
            fields=[
                ('id_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=250)),
                ('salary', models.IntegerField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to=jobapply.models.user_picture_directory_path)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('name_title', models.CharField(blank=True, max_length=50)),
                ('firstname', models.CharField(blank=True, max_length=250)),
                ('lastname', models.CharField(blank=True, max_length=250)),
                ('bdate', models.DateField(blank=True)),
                ('blood', models.CharField(blank=True, max_length=5)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('military_status', models.CharField(blank=True, max_length=100, null=True)),
                ('military_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('mobile_no', models.CharField(blank=True, max_length=50)),
                ('home_no', models.CharField(blank=True, max_length=50)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('line', models.CharField(blank=True, max_length=100)),
                ('check_study', models.CharField(blank=True, max_length=20, null=True)),
                ('nowEdu_level', models.CharField(blank=True, max_length=250, null=True)),
                ('nowEdu_instituteName', models.CharField(blank=True, max_length=300, null=True)),
                ('nowEdu_major', models.CharField(blank=True, max_length=250, null=True)),
                ('nowEdu_gpa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCertExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(blank=True, max_length=250)),
                ('experience_institute', models.CharField(blank=True, max_length=250)),
                ('experience_cert', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateComputerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateHistoryEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_level', models.CharField(blank=True, max_length=250, null=True)),
                ('edu_country', models.CharField(blank=True, max_length=250, null=True)),
                ('edu_instituteName', models.CharField(blank=True, max_length=250, null=True)),
                ('edu_fromYear', models.CharField(blank=True, max_length=10, null=True)),
                ('edu_toYear', models.CharField(blank=True, max_length=10, null=True)),
                ('edu_major', models.CharField(blank=True, max_length=250, null=True)),
                ('edu_gpa', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_language', models.CharField(blank=True, max_length=100)),
                ('skill_language_typing', models.CharField(blank=True, max_length=10)),
                ('skill_language_listen', models.CharField(blank=True, max_length=100)),
                ('skill_language_speak', models.CharField(blank=True, max_length=100)),
                ('skill_language_read', models.CharField(blank=True, max_length=100)),
                ('skill_language_write', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_companyName', models.CharField(blank=True, max_length=250)),
                ('experience_companyType', models.CharField(blank=True, max_length=250)),
                ('experience_companyStartDate', models.CharField(blank=True, max_length=20)),
                ('experience_companyEndDate', models.CharField(blank=True, max_length=20)),
                ('experience_companyPosition', models.CharField(blank=True, max_length=250)),
                ('experience_companySalary', models.CharField(blank=True, max_length=15)),
                ('experience_companyReason', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_cert_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateCertExperience'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_computer_skill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateComputerSkill'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_history_education',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateHistoryEducation'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_language_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateLanguageSkill'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateWorkExperience'),
        ),
        migrations.AddField(
            model_name='candidateattachment',
            name='candidate_basic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateBasic'),
        ),
    ]
