# Generated by Django 2.0.6 on 2018-08-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_resume', models.FileField(upload_to='')),
                ('attach_transcript', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Basic',
            fields=[
                ('id_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=250, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('name_title', models.CharField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=250, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('bdate', models.DateField(null=True)),
                ('blood', models.CharField(max_length=5, null=True)),
                ('race', models.CharField(max_length=100, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Cert_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_name', models.CharField(max_length=250)),
                ('experience_institute', models.CharField(max_length=250)),
                ('experience_cert', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Computer_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('mobile_no', models.CharField(max_length=50)),
                ('home_no', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=150)),
                ('line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_History_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_level', models.CharField(max_length=250, null=True)),
                ('edu_country', models.CharField(max_length=250, null=True)),
                ('edu_instituteName', models.CharField(max_length=250, null=True)),
                ('edu_fromYear', models.CharField(max_length=10, null=True)),
                ('edu_toYear', models.CharField(max_length=10, null=True)),
                ('edu_major', models.CharField(max_length=250, null=True)),
                ('edu_gpa', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Language_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_language', models.CharField(max_length=100)),
                ('skill_language_typing', models.IntegerField()),
                ('skill_language_listen', models.CharField(max_length=100)),
                ('skill_language_speak', models.CharField(max_length=100)),
                ('skill_language_read', models.CharField(max_length=100)),
                ('skill_language_write', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Military',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('military_status', models.CharField(max_length=100, null=True)),
                ('military_reason', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Now_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_study', models.CharField(max_length=10)),
                ('nowEdu_level', models.CharField(max_length=250, null=True)),
                ('nowEdu_instituteName', models.CharField(max_length=300, null=True)),
                ('nowEdu_major', models.CharField(max_length=250, null=True)),
                ('nowEdu_gpa', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Work_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_companyName', models.CharField(max_length=250)),
                ('experience_companyType', models.CharField(max_length=250)),
                ('experience_companyStartDate', models.DateField()),
                ('experience_companyEndDate', models.DateField()),
                ('experience_companyPosition', models.CharField(max_length=250)),
                ('experience_companySalary', models.IntegerField()),
                ('experience_companyReason', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='candidate_basic',
            name='candidate_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.Candidate_Contact'),
        ),
        migrations.AddField(
            model_name='candidate_basic',
            name='candidate_military',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.Candidate_Military'),
        ),
        migrations.AddField(
            model_name='candidate_basic',
            name='candidate_now_education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.Candidate_Now_Education'),
        ),
    ]
