# Generated by Django 2.0.6 on 2018-08-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate_contact',
            old_name='phone_no',
            new_name='home_no',
        ),
    ]
