# Generated by Django 2.0.6 on 2018-10-04 09:15

from django.db import migrations, models
import jobapply.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0002_auto_20181004_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebasic',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=500, upload_to=jobapply.models.user_picture_directory_path),
        ),
    ]
