# Generated by Django 2.0.6 on 2018-08-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0002_auto_20180826_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_basic',
            name='bdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='blood',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='firstname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='lastname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='name_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='position',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='race',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='religion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate_basic',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
