# Generated by Django 2.0.6 on 2018-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0002_auto_20180902_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebasic',
            name='nowEdu_gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidatehistoryeducation',
            name='edu_gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
