# Generated by Django 2.0.6 on 2018-09-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0003_auto_20180902_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelanguageskill',
            name='skill_language_typing',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidateworkexperience',
            name='experience_companySalary',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
