# Generated by Django 2.1.2 on 2018-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0003_auto_20181004_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
                ('converted', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
