# Generated by Django 2.0.6 on 2018-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0003_auto_20180826_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_now_education',
            name='nowEdu_gpa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_now_education',
            name='nowEdu_instituteName',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_now_education',
            name='nowEdu_level',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_now_education',
            name='nowEdu_major',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
