# Generated by Django 2.0.6 on 2018-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0004_auto_20180902_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateworkexperience',
            name='experience_companyEndDate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateworkexperience',
            name='experience_companyStartDate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
