# Generated by Django 2.0.6 on 2018-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0004_auto_20180826_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_fromYear',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_gpa',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_instituteName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_level',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_major',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history_education',
            name='edu_toYear',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
