# Generated by Django 2.0.6 on 2018-08-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0005_auto_20180826_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_basic',
            name='candidate_attachment',
        ),
        migrations.RemoveField(
            model_name='candidate_basic',
            name='candidate_cert_experience',
        ),
        migrations.RemoveField(
            model_name='candidate_basic',
            name='candidate_computer_skill',
        ),
        migrations.RemoveField(
            model_name='candidate_basic',
            name='candidate_history_education',
        ),
        migrations.RemoveField(
            model_name='candidate_basic',
            name='candidate_language_skill',
        ),
        migrations.RemoveField(
            model_name='candidate_basic',
            name='candidate_work_experience',
        ),
    ]
