# Generated by Django 2.0.6 on 2018-10-16 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0005_auto_20181016_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatebasic',
            name='nowEdu_level_new',
        ),
        migrations.AlterField(
            model_name='candidatebasic',
            name='nowEdu_level',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.EducationLevel'),
        ),
    ]
