# Generated by Django 2.0.6 on 2018-09-02 14:42

from django.db import migrations, models
import django.db.models.deletion
import jobapply.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0005_auto_20180902_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateAttachment'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_cert_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateCertExperience'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_language_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateLanguageSkill'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='candidate_work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapply.CandidateWorkExperience'),
        ),
        migrations.AlterField(
            model_name='candidateattachment',
            name='attach_transcript',
            field=models.FileField(blank=True, upload_to=jobapply.models.user_attachment_directory_path),
        ),
    ]
