# Generated by Django 2.0.6 on 2018-10-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0006_auto_20181016_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebasic',
            name='nowEdu_level_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='candidatebasic',
            name='nowEdu_level',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
