# Generated by Django 2.0.6 on 2018-10-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0013_auto_20181016_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebasic',
            name='nowEdu_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.EducationLevel'),
        ),
    ]
