# Generated by Django 2.0.6 on 2018-10-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0014_auto_20181016_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatebasic',
            name='candidate_history_education',
        ),
        migrations.AddField(
            model_name='candidatehistoryeducation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.CandidateBasic'),
        ),
    ]
