# Generated by Django 2.1.2 on 2018-10-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0015_auto_20181016_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatebasic',
            name='candidate_cert_experience',
        ),
        migrations.RemoveField(
            model_name='candidatebasic',
            name='candidate_language_skill',
        ),
        migrations.RemoveField(
            model_name='candidatebasic',
            name='candidate_work_experience',
        ),
        migrations.AddField(
            model_name='candidatecertexperience',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.CandidateBasic'),
        ),
        migrations.AddField(
            model_name='candidatelanguageskill',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.CandidateBasic'),
        ),
        migrations.AddField(
            model_name='candidateworkexperience',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.CandidateBasic'),
        ),
    ]
