# Generated by Django 2.0.6 on 2018-10-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0016_auto_20181016_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecomputerskill',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
