# Generated by Django 2.0.6 on 2018-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0017_auto_20181017_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
    ]
