# Generated by Django 2.0.6 on 2018-10-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0018_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryCode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=45)),
                ('currencyCode', models.CharField(max_length=3)),
            ],
        ),
    ]
