# Generated by Django 2.0.6 on 2018-10-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0020_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
