# Generated by Django 2.0.6 on 2018-10-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0021_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryCode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('currencyCode', models.CharField(blank=True, max_length=3, null=True)),
                ('countryNameENG', models.CharField(blank=True, max_length=200, null=True)),
                ('countryNameTH', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
