# Generated by Django 2.0.6 on 2018-10-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0022_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='CountryDetail',
        ),
    ]
