# Generated by Django 2.0.6 on 2018-10-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0024_auto_20181019_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('skill_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
