# Generated by Django 2.0.6 on 2018-10-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0026_auto_20181019_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatehistoryeducation',
            name='edu_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.Country'),
        ),
    ]
