# Generated by Django 2.0.6 on 2018-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0028_auto_20181029_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSkill',
            fields=[
                ('extra_skill_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='com_skill',
            field=models.ManyToManyField(blank=True, to='jobapply.Skill'),
        ),
        migrations.AddField(
            model_name='candidatebasic',
            name='extra_com_skill',
            field=models.ManyToManyField(blank=True, to='jobapply.ExtraSkill'),
        ),
    ]
