# Generated by Django 2.0.6 on 2018-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0029_auto_20181029_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
