# Generated by Django 2.0.6 on 2018-11-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0031_auto_20181030_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebasic',
            name='nowEdu_instituteName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecomputerskill',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidateworkexperience',
            name='experience_companyReason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='country',
            name='countryCode',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
