# Generated by Django 2.0.6 on 2018-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0032_auto_20181116_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebasic',
            name='bdate',
            field=models.DateTimeField(),
        ),
    ]
