# Generated by Django 2.0.6 on 2018-11-16 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0035_remove_candidatebasic_bdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebasic',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
