# Generated by Django 2.0.6 on 2018-10-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
