# Generated by Django 2.0.6 on 2018-10-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidaterank',
            options={'permissions': (('can_add_candidate_rank', 'create_candidate_rank'),)},
        ),
    ]
