# Generated by Django 2.0.6 on 2018-10-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20181010_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidaterank',
            options={},
        ),
    ]
