# Generated by Django 2.1.2 on 2018-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20181010_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
