# Generated by Django 2.1.2 on 2018-10-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_candidateranks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateRanks',
        ),
    ]
