# Generated by Django 2.0.6 on 2018-10-11 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_delete_candidateranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterank',
            name='candidate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapply.CandidateBasic'),
        ),
    ]
