# Generated by Django 2.0.6 on 2018-10-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_auto_20181011_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterank',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
