# Generated by Django 2.0.6 on 2018-10-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_auto_20181011_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterank',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
