# Generated by Django 2.0.6 on 2018-10-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_cart', '0002_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_ordered',
        ),
    ]
