# Generated by Django 2.0.6 on 2018-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_cart', '0003_auto_20181026_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
    ]
