# Generated by Django 2.0.6 on 2018-10-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_cart', '0004_auto_20181026_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
