# Generated by Django 2.0.6 on 2018-11-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_cart', '0006_auto_20181106_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStatus',
            fields=[
                ('status_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='interview_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate_cart.InterviewStatus'),
        ),
    ]
