# Generated by Django 2.0.6 on 2018-11-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('candidate_cart', '0009_auto_20181106_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_update_status', models.DateTimeField(auto_now_add=True)),
                ('interview_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate_cart.InterviewStatus')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='interview_status_log',
            field=models.ManyToManyField(blank=True, to='candidate_cart.InterviewStatusLog'),
        ),
    ]
