# Generated by Django 2.0.6 on 2018-10-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, to='wishlist.WishlistItem'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='date_wishlist_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
