# Generated by Django 2.0.6 on 2018-11-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addskill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('abstract', models.CharField(blank=True, max_length=5, null=True)),
                ('body', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5, null=True)),
                ('abstract', models.CharField(blank=True, max_length=5, null=True)),
                ('body', models.CharField(blank=True, max_length=5, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addskill.Post')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
