# Generated by Django 2.0.6 on 2018-11-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addskill', '0002_post_posthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthistory',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostHistory',
        ),
    ]
