# Generated by Django 2.0.6 on 2018-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('tor_amount', models.IntegerField(blank=True, null=True)),
                ('now_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
