# Generated by Django 2.0.6 on 2018-11-08 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_site', models.CharField(blank=True, max_length=100, null=True)),
                ('project_tor_amount', models.IntegerField(blank=True, null=True)),
                ('project_now_amount', models.IntegerField(blank=True, null=True)),
                ('requirement', models.CharField(blank=True, max_length=300, null=True)),
                ('certification', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=15)),
                ('level_name', models.CharField(max_length=100)),
                ('level_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type_id', models.CharField(max_length=15)),
                ('project_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='tor',
            old_name='position',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='tor',
            old_name='now_amount',
            new_name='position_now_amount',
        ),
        migrations.RenameField(
            model_name='tor',
            old_name='tor_amount',
            new_name='position_tor_amount',
        ),
        migrations.AddField(
            model_name='tor',
            name='job_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tor',
            name='job_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tor',
            name='position_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='positionproject',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.ProjectLevel'),
        ),
        migrations.AddField(
            model_name='positionproject',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.ProjectType'),
        ),
        migrations.AddField(
            model_name='tor',
            name='position_project',
            field=models.ManyToManyField(blank=True, to='tor.PositionProject'),
        ),
    ]
