# Generated by Django 2.0.6 on 2018-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0003_auto_20181108_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tor',
            name='position_edu_des',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tor',
            name='position_exp_des',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tor',
            name='position_role_des',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
