# Generated by Django 2.0.6 on 2018-11-10 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0004_auto_20181108_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionproject',
            name='datetime_add_project',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionproject',
            name='datetime_update_project',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tor',
            name='datetime_add_position',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tor',
            name='datetime_update_position',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
