# Generated by Django 2.0.6 on 2018-11-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0006_positionfield_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=5)),
                ('position_name', models.CharField(max_length=150)),
            ],
        ),
    ]
