# Generated by Django 2.0.6 on 2018-11-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0007_positionall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionfield',
            name='position_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Position_In_Project', to='tor.PositionAll'),
        ),
    ]
