# Generated by Django 2.0.6 on 2018-11-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0009_auto_20181114_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionfield',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='positionfield',
            name='requirement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='positionproject',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='positionproject',
            name='requirement',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tor',
            name='position_edu_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tor',
            name='position_exp_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tor',
            name='position_role_des',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
