# Generated by Django 2.0.6 on 2018-11-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0010_auto_20181116_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionproject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='positionproject',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='tor',
            name='position_project',
        ),
        migrations.DeleteModel(
            name='PositionProject',
        ),
        migrations.DeleteModel(
            name='Tor',
        ),
    ]
