# Generated by Django 2.0.6 on 2018-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20181025_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcandidate',
            name='vacancy_employee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
