# Generated by Django 2.0.6 on 2018-10-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20181025_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcandidate',
            name='date_request',
        ),
    ]
