# Generated by Django 2.0.6 on 2018-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_requestcandidate_date_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcandidate',
            name='now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
