# Generated by Django 2.0.6 on 2018-10-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_requestcandidate_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcandidate',
            name='now',
        ),
    ]
