# Generated by Django 2.0.6 on 2018-10-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_remove_requestcandidate_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcandidate',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.Status'),
        ),
    ]
