# Generated by Django 2.0.6 on 2018-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_requestcandidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcandidate',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
