# Generated by Django 2.0.6 on 2018-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20181026_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='request_owner',
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime_comment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcandidate',
            name='comment',
            field=models.ManyToManyField(to='request.Comment'),
        ),
        migrations.AddField(
            model_name='requestcandidate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
