# Generated by Django 2.0.6 on 2018-10-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_auto_20181026_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcandidate',
            old_name='date_request',
            new_name='datetime_add_request',
        ),
        migrations.RenameField(
            model_name='requestcandidate',
            old_name='updated',
            new_name='datetime_update_request',
        ),
    ]
