# Generated by Django 2.0.6 on 2018-10-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_auto_20181028_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='last_comment_owner',
        ),
        migrations.RemoveField(
            model_name='request',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_candidate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_interview',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requestcandidate',
            name='level',
        ),
        migrations.RemoveField(
            model_name='requestcandidate',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='requestinterview',
            name='order',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='RequestCandidate',
        ),
        migrations.DeleteModel(
            name='RequestInterview',
        ),
    ]
