# Generated by Django 2.0.6 on 2018-10-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_cart', '0005_auto_20181028_0128'),
        ('account', '0001_initial'),
        ('request', '0016_auto_20181028_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=15)),
                ('request_title', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime_add_request', models.DateTimeField(auto_now_add=True)),
                ('datetime_update_request', models.DateTimeField(auto_now=True)),
                ('comment', models.ManyToManyField(blank=True, to='request.Comment')),
                ('last_comment_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updater', to='account.Profile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='account.Profile')),
            ],
            options={
                'ordering': ['datetime_add_request'],
            },
        ),
        migrations.CreateModel(
            name='RequestCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_site', models.CharField(blank=True, max_length=100, null=True)),
                ('tor_employee_amount', models.IntegerField(blank=True, null=True)),
                ('now_employee_amount', models.IntegerField(blank=True, null=True)),
                ('vacancy_employee_amount', models.IntegerField(blank=True, null=True)),
                ('requirement', models.CharField(blank=True, max_length=300, null=True)),
                ('certification', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.LevelRequest')),
                ('project_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.ProjectType')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interview', models.CharField(max_length=100)),
                ('note_interview', models.CharField(max_length=100)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate_cart.Order')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='request_candidate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.RequestCandidate'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.RequestInterview'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.RequestType'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.Status'),
        ),
    ]
