# Generated by Django 2.0.6 on 2018-10-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20181028_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.RequestCandidate'),
        ),
        migrations.AlterField(
            model_name='requestinterview',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate_cart.Order'),
        ),
    ]
