# Generated by Django 2.0.6 on 2018-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20181028_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=5)),
                ('position_name', models.CharField(max_length=150)),
            ],
        ),
    ]
