# Generated by Django 2.0.6 on 2018-11-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_auto_20181106_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcandidate',
            name='level',
        ),
        migrations.DeleteModel(
            name='LevelRequest',
        ),
    ]
