# Generated by Django 2.0.6 on 2018-11-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_auto_20181114_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcandidate',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
