# Generated by Django 2.0.6 on 2018-11-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0009_auto_20181114_1844'),
        ('request', '0023_auto_20181114_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcandidate',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='requestcandidate',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='requestcandidate',
            name='vacancy_employee_amount',
        ),
        migrations.AddField(
            model_name='requestcandidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.PositionField'),
        ),
        migrations.AddField(
            model_name='requestcandidate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.Project'),
        ),
    ]
