# Generated by Django 2.0.6 on 2018-11-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_auto_20181116_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=20),
        ),
    ]
