# Generated by Django 2.0.6 on 2018-11-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0026_auto_20181116_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=40),
        ),
    ]
