# Generated by Django 2.0.6 on 2018-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_auto_20181116_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
