# Generated by Django 2.0.6 on 2018-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_auto_20181118_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateAmountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_amount', models.IntegerField(blank=True, null=True)),
                ('datetime_add_amount', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='requestcandidate',
            name='update_amount_log',
            field=models.ManyToManyField(blank=True, to='request.UpdateAmountLog'),
        ),
    ]
