# Generated by Django 2.0.6 on 2018-11-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0030_updateamountlog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcandidate',
            name='empty_employee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcandidate',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
